### ISSUE TITLE
[BUG] [GPU] AMD Ryzen 7840: No supported GPU has been found inside your system.

### ISSUE THREAD

**Issue by McCrafterIV** [H3rz3n/davinci-helper#35]
The AMD Ryzen 7 7840HS does not seem to be supported by the helper. Trying to run resolve results in a segmentation fault
```
ActCCMessage Already in Table: Code= c005, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= c006, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= c007, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= 2282, Mode=  0, Level=  0, CmdKey= 8, Option= 0
19.1.1.0008 Linux/Clang x86_64
Main thread starts: 275DA000
Segmentation fault (core dumped)

```

Running on a quite fresh install of Fedora 41.

I installed some drivers manually, which didn't help either
```
sudo usermod -a -G render,video $LOGNAME
sudo dnf -y install rocm-opencl rocminfo rocm-clinfo rocm-hip rocm-runtime rocm-smi rocm-hip-devel
```

**Comment by McCrafterIV** [comment]
After some further debugging I noticed that davinci starts if I run the program as root. Playing video doesn't seem to work though

**Comment by De-Clan-C** [comment]
Make sure the rocm-opencl driver is from the updates repo. There was another one I installed that didn't work, but this one did. To check run `dnf list rocm-opencl` I'm on Fedora 41 with an RX 580.

**Comment by McCrafterIV** [comment]
Running the command returns
`rocm-opencl.x86_64 2.0.0.60203-124.el9 rocm`
I'm a bit stuck on checking if this is the correct repo. How should I move forward?

**Comment by McCrafterIV** [comment]
I reinstalled the driver from the updates repo, Davinci is still not starting and davinci helper is still returning the same error response.

```
$ dnf list rocm-opencl
rocm-opencl.x86_64 6.2.1-5.fc41 updates


```

**Comment by H3rz3n** [comment]
Hi ! Thank you for using DaVinci Helper. I'm sorry to heart that you're experiencing a bug. Can you please provide me the output of `lspci | grep -Ei 'vga|display` ?

**Comment by McCrafterIV** [comment]
There was a connection issue between, got the gpu detection working now. Just for reference, the output was
`03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 33 [Radeon RX 7600/7600 XT/7600M XT/7600S/7700S / PRO W7600] (rev c1)
`

Resolve still isn't starting though, I'm still receiving the segfault error as mentioned in the original bug report.

**Comment by H3rz3n** [comment]
Thank you  all for reporting me this issue, I've fixed it in the new release `v2.3.2` of DaVinci Helper. Please let me know if your problem is correctly solved (^_^).

**Comment by McCrafterIV** [comment]
Thanks for the quick response! The GPU is detected correctly now but davinci still doesn't start. I've completely reinstalled resolve using DavinciHelper (doing the actual installing step manually due to the helper not recognizing my installation file). Resolve complains about zlib being missing from the system. This is the complete output from the installation:

```
DaVinci_Resolve_19.1.1_Linux.run 
egrep: warning: egrep is obsolescent; using grep -E
Error: Missing or outdated system packages detected.

Please install the following missing packages:
    zlib

Use SKIP_PACKAGE_CHECK=1 to bypass the system package check.

***********************
Installation cancelled.

```

I could skip this using the SKIP_PACKAGE_CHECK variable and complete all steps successfully according to DavinciHelper. Davinci still shows the same seg fault error when I try to start it with a normal user.

Let me know if there is any information I can provide that will be helpful!

Please reopen the issue @H3rz3n as I'm not allowed to do so.

**Comment by H3rz3n** [comment]
Can you try to use the latest version I published a few minutes ago ? It's `v2.3.4`

**Comment by McCrafterIV** [comment]
I've tried with `v2.3.5`. All the installation steps completed successfully. Resolve still doesnt start, failing with seg fault as before.

**Comment by H3rz3n** [comment]
What version of DaVinci Resolve are you using ? Your problem is not with DaVinci Helper, but if I can I will try to help you (^_^).

**Comment by McCrafterIV** [comment]
I'm trying to install Davinci 19.1.1 but had the same issues with version 18

**Comment by H3rz3n** [comment]
It's very strange, I can suggest you to try to install it inside a live session from the USB just to ensure if your Fedora installation has some problems.

**Comment by McCrafterIV** [comment]
I've tried over many different installations so I don't think this would work. I will still try it and report back in one or two days. Any other ideas?

**Comment by H3rz3n** [comment]
I'm sorry to say that I don't have more ideas for know. Testing with a live USB will make all the difference between a problem with DaVinci or a problem with your Fedora / hardware config
